_target_: planning.mpc.MPCPlanner
max_iter: 5  # MPC iterations (how many times to replan)
n_taken_actions: 5  # Actions from planned sequence to execute before replanning
sub_planner:
  target: planning.cem.CEMPlanner
  horizon: 5  # CEM plans 5-step action sequences
  topk: 10  # Number of elite sequences to keep (10%)
  num_samples: 100  # Number of samples CEM takes
  var_scale: 1
  opt_steps: 10  # Number of optimization steps CEM runs
  eval_every: 1

name: mpc_cem